### ISSUE TITLE
Just a question. Are you using this DNS server in production?

### ISSUE THREAD

**Issue by abpin** [damoun/dnsserver.js#1]
Hi, 

Wanted to drop by , say Hi, and ask you about the usage of this DNS in node.js
I am interested  to know the status of this code and how it is being used before investing time into it. 

Thanks
abPIN

**Comment by damoun** [comment]
Hi :)

No, this server is not in production. Maybe one day on a home server.
Any test was performed so I don't know the performance but you can try.

This project was to understand the RFC but I will continue to work on (miss one important part of the RFC, the compression) :)
